Update to use AppBarConfiguration
googlecodelabs/android-navigation pull request #40
Opened 2018-12-06 23:15 UTC by ceruleanotter

Adding [AppBarConfiguration](https://developer.android.com/reference/androidx/navigation/ui/AppBarConfiguration) to code and updating dependencies.

2018-12-07 23:24 UTC, ianhanniballake requested changes

2018-12-07 23:24 UTC, ianhanniballake commented on app/src/main/java/com/example/android/codelabs/navigation/MainActivity.kt
> +//        val appBarConfiguration = AppBarConfiguration(navController.graph, drawerLayout)
`navController.graph` should probably be `setOf(R.id.home_dest, R.id.deeplink_dest)` so that the up button isn't shown on either of those top level destinations.

2018-12-07 23:24 UTC, ianhanniballake commented on app/src/main/java/com/example/android/codelabs/navigation/MainActivity.kt
> +//        return findNavController(R.id.my_nav_host_fragment).navigateUp(drawerLayout)
If you do make the above change to use `setOf(R.id.home_dest, R.id.deeplink_dest)` instead of `navController.graph`, you need to do the same thing here to ensure that the up button when using the `DrawerLayout` (i.e., when in multi-window mode on phones) does the right thing.

2018-12-08 01:31 UTC, ceruleanotter commented on app/src/main/java/com/example/android/codelabs/navigation/MainActivity.kt
> +//        val appBarConfiguration = AppBarConfiguration(navController.graph, drawerLayout)
Update pushed for this, thanks!

2018-12-08 01:31 UTC, ceruleanotter commented on app/src/main/java/com/example/android/codelabs/navigation/MainActivity.kt
> +//        return findNavController(R.id.my_nav_host_fragment).navigateUp(drawerLayout)
Update pushed for this, thanks!

2018-12-08 04:40 UTC, ianhanniballake approved these changes

2018-12-11 01:51 UTC, merged